
CREATE TABLE IF NOT EXISTS `cours` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(65) NOT NULL,
  `desc` MEDIUMTEXT NULL,
  `url` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `duration` INT NOT NULL,
  `teacher` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `date_UNIQUE` (`date` ASC) VISIBLE,
  UNIQUE INDEX `url_UNIQUE` (`url` ASC) VISIBLE
);
